name: learn_env
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _py-xgboost-mutex=2.0
  - arrow-cpp=17.0.0
  - autopep8=2.0.4
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - boost-cpp=1.82.0
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - colorama=0.4.6
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cyrus-sasl=2.1.28
  - dataclasses=0.8
  - datasets=2.2.1
  - dbus=1.13.18
  - dill=0.3.9
  - docstring-to-markdown=0.16
  - et_xmlfile=2.0.0
  - expat=2.5.0
  - ffmpeg=4.3
  - flake8=7.0.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - fsspec=2025.3.2
  - geographiclib=2.0
  - geopy=2.4.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.5.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - html5lib=1.1
  - httpcore=1.0.7
  - httpx=0.28.1
  - huggingface_hub=0.30.2
  - hyperframe=6.1.0
  - icu=73.1
  - imbalanced-learn=0.12.0
  - importlib-metadata=8.6.1
  - importlib_metadata=8.6.1
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - isort=5.13.2
  - joblib=1.4.2
  - jpeg=9e
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.1.5
  - jupyterlab-lsp=5.1.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.9
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcups=2.4.2
  - libcurand=10.3.4.107
  - libcurl=8.9.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxgboost=1.7.3
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.8.0
  - mccabe=0.7.0
  - mkl=2023.1.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mysql=5.7.24
  - ncurses=6.4
  - nettle=3.7.3
  - nodejs=18.18.2
  - numpy-base=1.26.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.16
  - orc=2.0.1
  - patsy=1.0.1
  - pcre=8.45
  - pluggy=1.5.0
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.43
  - pure_eval=0.2.2
  - py-xgboost=1.7.3
  - pycodestyle=2.11.1
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pylint=3.0.4
  - pyqt=5.15.10
  - python=3.11.7
  - python-fastjsonschema=2.16.2
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.10.1
  - python-lsp-server-base=1.10.1
  - python-tzdata=2023.3
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - responses=0.18.0
  - retrying=1.3.3
  - rope=1.13.0
  - s2n=1.3.27
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - snappy=1.2.1
  - snowballstemmer=2.2.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=3.6.0
  - tk=8.6.12
  - tomli=2.2.1
  - tomlkit=0.13.2
  - torchtriton=2.1.0
  - typing_extensions=4.9.0
  - utf8proc=2.6.1
  - whatthepatch=1.0.7
  - xz=5.4.5
  - yaml=0.2.5
  - yapf=0.43.0
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - accelerate==0.33.0
    - aiohappyeyeballs==2.3.5
    - aiohttp==3.10.3
    - aiosignal==1.3.1
    - angle-emb==0.4.12
    - anyio==3.5.0
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - astroid==3.0.3
    - asttokens==2.0.5
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.11.0
    - beautifulsoup4==4.12.2
    - bitsandbytes==0.43.0
    - bleach==4.1.0
    - boltons==23.1.1
    - bottleneck==1.3.5
    - brotli==1.0.9
    - catppuccin-jupyterlab==0.2.0
    - cattrs==23.2.3
    - cffi==1.16.0
    - charset-normalizer==2.0.4
    - click==8.1.7
    - cloudpickle==3.1.1
    - comm==0.1.2
    - contourpy==1.2.0
    - cryptography==41.0.7
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - entrypoints==0.4
    - ete3==3.1.3
    - executing==0.8.3
    - fastjsonschema==2.16.2
    - filelock==3.13.1
    - fonttools==4.25.0
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - gitdb==4.0.11
    - gitpython==3.1.42
    - gmpy2==2.1.2
    - huggingface-hub==0.24.5
    - idna==3.4
    - ipykernel==6.28.0
    - ipython==8.20.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jedi==0.19.1
    - jedi-language-server==0.41.3
    - jinja2==3.1.2
    - json5==0.9.6
    - jsonpointer==2.4
    - jsonschema==4.19.2
    - jsonschema-specifications==2023.7.1
    - jupyter==1.0.0
    - jupyter-client==8.6.0
    - jupyter-console==6.6.3
    - jupyter-core==5.5.0
    - jupyter-events==0.8.0
    - jupyter-server==2.10.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-darkside-theme==0.1.2
    - jupyterlab-execute-time==3.1.2
    - jupyterlab-materialdarker-theme==0.1.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.25.1
    - jupyterlab-widgets==3.0.9
    - kiwisolver==1.4.4
    - llvmlite==0.44.0
    - lsprotocol==2023.0.1
    - lxml==4.9.3
    - markupsafe==2.1.3
    - matplotlib==3.8.0
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - multidict==6.0.5
    - multiprocess==0.70.16
    - munkres==1.1.4
    - narwhals==2.5.0
    - nbclassic==0.5.6
    - nbclient==0.8.0
    - nbconvert==7.10.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.6
    - networkx==3.1
    - notebook==7.1.2
    - notebook-shim==0.2.3
    - numba==0.61.2
    - numexpr==2.8.7
    - numpy==1.26.3
    - openpyxl==3.0.10
    - overrides==7.4.0
    - packaging==23.1
    - pandas==2.1.4
    - pandocfilters==1.5.0
    - parso==0.8.3
    - peft==0.10.0
    - pexpect==4.8.0
    - pillow==10.0.1
    - pip==23.3.1
    - platformdirs==3.10.0
    - plotly==6.3.0
    - ply==3.11
    - prettytable==3.10.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.43
    - protobuf==4.25.3
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==17.0.0
    - pyarrow-hotfix==0.6
    - pycocotools==2.0.7
    - pycparser==2.21
    - pygls==1.3.0
    - pygments==2.15.1
    - pymupdf==1.23.23
    - pymupdfb==1.23.22
    - pynndescent==0.5.13
    - pyopenssl==23.2.0
    - pyparsing==3.0.9
    - pyqt5==5.15.10
    - pyqt5-sip==12.13.0
    - pyreadr==0.5.3
    - pysocks==1.7.1
    - pytesseract==0.3.13
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-jsonrpc-server==0.4.0
    - pytoolconfig==1.3.1
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - qtconsole==5.5.0
    - qtpy==2.4.1
    - referencing==0.30.2
    - regex==2023.12.25
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.6
    - safetensors==0.4.4
    - scikit-learn==1.2.2
    - scipy==1.15.2
    - send2trash==1.8.2
    - sentry-sdk==1.43.0
    - setproctitle==1.3.3
    - setuptools==68.2.2
    - shap==0.47.2
    - sip==6.7.12
    - six==1.16.0
    - slicer==0.0.8
    - smmap==5.0.1
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.2.0
    - statsmodels==0.14.4
    - sympy==1.12
    - terminado==0.17.1
    - testpath==0.6.0
    - theme-darcula==4.0.0
    - tinycss2==1.2.1
    - tokenizers==0.19.1
    - torch==2.1.2
    - torch-summary==1.4.5
    - torchaudio==2.1.2
    - torchvision==0.16.2
    - tornado==6.3.3
    - tqdm==4.66.5
    - traitlets==5.7.1
    - transformers==4.42.4
    - triton==2.1.0
    - types-python-dateutil==2.9.0.20240316
    - typing-extensions==4.9.0
    - tzdata==2023.3
    - ujson==5.10.0
    - umap-learn==0.5.7
    - uri-template==1.3.0
    - urllib3==1.26.18
    - wandb==0.16.5
    - wcwidth==0.2.5
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==0.58.0
    - wheel==0.41.2
    - widgetsnbextension==4.0.5
    - xgboost==1.7.3
    - xxhash==3.5.0
    - yarl==1.11.0
    - zipp==3.18.1
